-- Inserción de comunas
INSERT INTO comunas (id, nombre, codigo, geometria) VALUES
    (1, 'Cerrillos', 'CL-RM-01', NULL),
    (2, 'Cerro Navia', 'CL-RM-02', NULL),
    (3, 'Conchalí', 'CL-RM-03', NULL),
    (4, 'El Bosque', 'CL-RM-04', NULL),
    (5, 'Estación Central', 'CL-RM-05', NULL),
    (6, 'Huechuraba', 'CL-RM-06', NULL),
    (7, 'Independencia', 'CL-RM-07', NULL),
    (8, 'La Cisterna', 'CL-RM-08', NULL),
    (9, 'La Florida', 'CL-RM-09', NULL),
    (10, 'La Granja', 'CL-RM-10', NULL),
    (11, 'La Pintana', 'CL-RM-11', NULL),
    (12, 'La Reina', 'CL-RM-12', NULL),
    (13, 'Las Condes', 'CL-RM-13', NULL),
    (14, 'Lo Barnechea', 'CL-RM-14', NULL),
    (15, 'Lo Espejo', 'CL-RM-15', NULL),
    (16, 'Lo Prado', 'CL-RM-16', NULL),
    (17, 'Macul', 'CL-RM-17', NULL),
    (18, 'Maipú', 'CL-RM-18', NULL),
    (19, 'Ñuñoa', 'CL-RM-19', NULL),
    (20, 'Pedro Aguirre Cerda', 'CL-RM-20', NULL),
    (21, 'Peñalolén', 'CL-RM-21', NULL),
    (22, 'Providencia', 'CL-RM-22', NULL),
    (23, 'Pudahuel', 'CL-RM-23', NULL),
    (24, 'Quilicura', 'CL-RM-24', NULL),
    (25, 'Quinta Normal', 'CL-RM-25', NULL),
    (26, 'Recoleta', 'CL-RM-26', NULL),
    (27, 'Renca', 'CL-RM-27', NULL),
    (28, 'San Joaquín', 'CL-RM-28', NULL),
    (29, 'San Miguel', 'CL-RM-29', NULL),
    (30, 'San Ramón', 'CL-RM-30', NULL),
    (31, 'Santiago', 'CL-RM-31', NULL),
    (32, 'Vitacura', 'CL-RM-32', NULL);
